### ISSUE TITLE
BertConfig object has no attribute pruned_layers_dim

### ISSUE THREAD

**Issue by akhauriyash** [Holldean/BERT-Pruning#1]
I ran 

bash factorize.sh 

factorize.sh is:
```
python ./flop/factorize.py \
  --bert_config_file=./uncased_L-12_H-768_A-12/bert_config.json \
  --checkpoint=/workspace/BERT-Pruning/output/fine_tune_outputs/SST-2/lr_3e-5/model.ckpt-6313 \
  --output_dir=./uncased_L-12_H-768_A-12_SST-2_f/bert_model_f.ckpt \
  --finetuned
```

I got the following error

```
Traceback (most recent call last):
  File "./flop/factorize.py", line 135, in <module>
    finetuned=args.finetuned)
  File "./flop/factorize.py", line 69, in save_factorized_model
    finetuned=finetuned)
  File "./flop/factorize.py", line 46, in create_model
    factorize=True)
  File "/workspace/BERT-Pruning/flop/modeling_flop.py", line 178, in __init__
    pruned_layers_dim=config.pruned_layers_dim)
AttributeError: 'BertConfig' object has no attribute 'pruned_layers_dim
```

Any comments / help would be really appreciated :)

**Comment by akhauriyash** [comment]
```

{
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522,
  "pruned_layers_dim": []
}

```

Does this fix it? (editing the bert_config.json to add the pruned_layers_dim attribute)

**Comment by Arexh** [comment]
Sorry to see your message now. The code does have such a bug. Adding the `pruned_layers_dim` attribute in the config file can be a solution. However, I have made a modification to the code and commit. This new code does not need to modify the config file.

**Comment by Arexh** [comment]
Thanks for finding this bug. If there are other problems, I am also willing to help you : )

**Comment by akhauriyash** [comment]
Hello,
Thank you for helping me with that fix, unfortunately I am getting this error still (I also got this error in the previous commit when I added :
  "pruned_layers_dim": []
  to the json config file.


 ```
INFO:tensorflow:Tensor: bert/encoder/layer_11/output/dense_p/kernel:0 *INIT_FROM_CKPT*
INFO:tensorflow:Tensor: bert/encoder/layer_11/output/dense_q/bias:0 *INIT_FROM_CKPT*
INFO:tensorflow:Tensor: bert/encoder/layer_11/output/dense_q/kernel:0 *INIT_FROM_CKPT*
WARNING:tensorflow:From ./flop/remove_mask.py:151: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

Traceback (most recent call last):
  File "./flop/remove_mask.py", line 182, in <module>
    threshold=args.threshold)
  File "./flop/remove_mask.py", line 157, in remove_mask
    1 - dense_pruned_params / dense_total_params),
ZeroDivisionError: division by zero
```


Do you know what I can do about it?
I printed this
`print("\n*****\n", dense_total_params, "\n", dense_pruned_params, "\n", dense_origin_params, "\n", non_kernel_params, "\n", total_params, "\n", pruned_total_params, "\n", total_params, "\n*****\n")`
and got the following output
```

*****
 0
 0
 0
 23959298
 23959298
 23959298
 23959298
*****
```

**Comment by Arexh** [comment]
It seems that the code `remove_mask.py` may have some problems, maybe I forgot to upload the latest code last year. I will figure out how to solve these problems these days.

**Comment by Arexh** [comment]
I ran through all five steps of the project (please see the `Structured Pruning` section of the README if you are unclear) and found that the code can run through. Probably because my README is not clear enough, it has brought you a lot of problems. Before running the code, please make sure your GPU memory is greater than 24GB.

1. In the first step, you need to finetune Google's BERT pretrained model on a task (SST-2 for example), using the following example command:
```bash
export ROOT_DIR=`pwd`
export BERT_BASE_DIR=$ROOT_DIR/uncased_L-12_H-768_A-12
export GLUE_DIR=$ROOT_DIR/datasets
export DATA_DIR=$ROOT_DIR

task_name="SST-2"

batch_size="32"
max_seq_length="128"
fine_tune_epoch="3.0"
learning_rate="3e-5"

cd bert

python run_classifier.py \
    --task_name=$task_name \
    --do_train=true \
    --do_eval=true \
    --data_dir=$GLUE_DIR/$task_name/ \
    --vocab_file=$BERT_BASE_DIR/vocab.txt \
    --bert_config_file=$BERT_BASE_DIR/bert_config.json \
    --init_checkpoint=$BERT_BASE_DIR/bert_model.ckpt \
    --max_seq_length=$max_seq_length \
    --train_batch_size=$batch_size \
    --learning_rate=$learning_rate \
    --num_train_epochs=$fine_tune_epoch \
    --output_dir=$DATA_DIR/fine_tune_outputs/$task_name/lr_$learning_rate
```

- Then you have an original finetuned BERT model in `$DATA_DIR/fine_tune_outputs/$task_name/lr_$learning_rate`.
2. Second step, run `factorize.sh` to factorize the BERT model into BERT-f:
- The path `./path/to/finetuned/model/bert_model.ckpt` should be same as `$DATA_DIR/fine_tune_outputs/$task_name/lr_$learning_rate` which you get in the first step.
- At this time, there is no `bert_config.json` and `vocab.txt` in the output directory `./uncased_L-12_H-768_A-12_SST-2_f`, you need to copy them from `./uncased_L-12_H-768_A-12`.
3. Then run `run.sh` (I have committed a new version) to train the mask layer, note that `--init_checkpoint=` should point to the path `./uncased_L-12_H-768_A-12_SST-2_f` in the second step.
- Since this part of the training time is long, you can set `fine_tune_epoch` to 1 for testing.
4. Run `remove_mask.sh`, the `--checkpoint` flag should point to the `output_dir` in the third step.
- When finish, `--output_folder_dir` will generate `bert_model_f`, a new `bert_config.json` with `pruned_layers_dim` property, and `info.txt`.
5. Finally, run this example command to finetune your pruned model which is in `output_folder_dir` in the forth step:
```bash
export BERT_DIR=`pwd`
export CHECKPOINT=uncased_L-12_H-768_A-12_SST-2_f
export OUTPUT_DIR=$BERT_DIR/Final-Model

task_name="SST-2"
batch_size="32"
max_seq_length="128"
fine_tune_epoch="1.0"
learning_rate="3e-5"
learning_rate_warmup="200"
lambda_lr="10.0"
alpha_lr="5.0"
target_sparsity="0.95"
target_sparsity_warmup="4000"
hidden_dropout_prob="0.1"
attention_probs_dropout_prob="0.1"
regularization_scale="0"
factorized="True"

python ./flop/run_classifier.py \
    --task_name=$task_name \
    --do_train=true \
    --do_eval=true \
    --data_dir=$BERT_DIR/datasets/$task_name/ \
    --vocab_file=$BERT_DIR/$CHECKPOINT/vocab.txt \
    --bert_config_file=$BERT_DIR/remove_output/bert_config.json \
    --init_checkpoint=$BERT_DIR/remove_output/bert_model_f.ckpt \
    --max_seq_length=$max_seq_length \
    --train_batch_size=$batch_size \
    --learning_rate=$learning_rate \
    --num_train_epochs=$fine_tune_epoch \
    --learning_rate_warmup=$learning_rate_warmup \
    --lambda_learning_rate=$lambda_lr \
    --alpha_learning_rate=$alpha_lr \
    --target_sparsity=$target_sparsity \
    --hidden_dropout_prob=$hidden_dropout_prob \
    --attention_probs_dropout_prob=$attention_probs_dropout_prob \
    --target_sparsity_warmup=$target_sparsity_warmup \
    --regularization_scale=$regularization_scale \
    --output_dir=$OUTPUT_DIR/$CHECKPOINT \
    --factorized=$factorized
```
- Note that in this step, the flag `--factorized=True` is necessary.

**Comment by Arexh** [comment]
I will find time to update the README and code~

**Comment by akhauriyash** [comment]
Okay, thanks @Holldean , I will try this soon and get back to you :)

**Comment by akhauriyash** [comment]
Hello @Holldean 
Another quick question. I downloaded the model from your repository instead (the download model here) link,
The .ckpt.meta file was missing from the download, so I copied the meta file from the _f stage (just in case that works). But I get the following error if i run the following code:
CODE
```
import tensorflow as tf
sess = tf.InteractiveSession()
saver = tf.train.import_meta_graph('bert_model_f.ckpt.meta')
saver.restore(sess, 'bert_model.cpkt')
g = tf.get_default_graph()
```
ERROR
```
>>> saver.restore(sess, 'bert_model.cpkt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xyz/.local/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1282, in restore
    checkpoint_prefix)
ValueError: The passed save_path is not a valid checkpoint: bert_model.cpkt
```

Any clue how I can inspect the weights of the checkpoint you have given?

**Comment by Arexh** [comment]
`bert_model_f` is just an intermediate model, not the pruned one. Also, the structure of final model from different training results are not the same. 
A short advice, you can try to load the download model using my code first, and then export the `.ckpt.meta` file. That might work

**Comment by akhauriyash** [comment]
Hey @Holldean ,

I understand that bert_model_f is an intermediate model, but in your download model link, there is no .ckpt.meta file, so I tried to use that one along with the bert_model.ckpt you have provided. 

I am sorry, but I do not exactly understand what you mean by 'load the download model using my code'. Can you kindly elaborate? (Which code of yours I should use)

Thanks a lot for the help!

**Comment by Arexh** [comment]
Hi @akhauriyash , here I use `bert_config.json` and `vocab.txt` files to define the model, just run `/flop/run_classifier.py` to load this model and evaluate on some tasks. When loading model successfully, you can modify my code to get the `.ckpt.meta` file.

**Comment by akhauriyash** [comment]
I dont think I need to modify the code to get the .ckpt.meta file. It is being automatically saved as this is printed at the end of running run.sh (I keep factorized=true) 
```
I0316 03:47:32.583339 140304483120896 basic_session_run_hooks.py:606] Saving checkpoints for 0 into /data1/bert_pruning_attempt/BERT-Pruning/SST-2_Pruning/uncased_L-12_H-768_A-12_SST-2_f/2021-03-16-03:46:41/model.ckpt.
```
I take the .ckpt.meta file from here, put it in the SST-2_85%_t=0.8 folder (after downloading from your repository)

Then I run the following code:
```
import tensorflow as tf
sess=tf.Session()    
saver = tf.train.import_meta_graph('bert_model.ckpt.meta')
saver.restore(sess, 'bert_model.ckpt')
```

```
>>> saver = tf.train.import_meta_graph('bert_model.ckpt.meta')
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
```

Can you please upload the whole model including the .ckpt.meta file in the **Download model here** section of your readme?
I am not too familiar with tensorflow but why did you not include the meta file in your model download?

Thank you for the help!

**Comment by akhauriyash** [comment]
I dont think I need to modify the code to get the .ckpt.meta file. It is being automatically saved as this is printed at the end of running run.sh (I keep factorized=true) 
```
I0316 03:47:32.583339 140304483120896 basic_session_run_hooks.py:606] Saving checkpoints for 0 into /data1/bert_pruning_attempt/BERT-Pruning/SST-2_Pruning/uncased_L-12_H-768_A-12_SST-2_f/2021-03-16-03:46:41/model.ckpt.
```
I take the .ckpt.meta file from here, put it in the SST-2_85%_t=0.8 folder (after downloading from your repository)

Then I run the following code:
```
import tensorflow as tf
sess=tf.Session()    
saver = tf.train.import_meta_graph('bert_model.ckpt.meta')
saver.restore(sess, 'bert_model.ckpt')
```

```
>>> saver = tf.train.import_meta_graph('bert_model.ckpt.meta')
INFO:tensorflow:Saver not created because there are no variables in the graph to restore
```

Can you please upload the whole model including the .ckpt.meta file in the **Download model here** section of your readme?
I am not too familiar with tensorflow but why did you not include the meta file in your model download?

Thank you for the help!

**Comment by Arexh** [comment]
Sorry @akhauriyash , since I'm a bit busy lately, I have no time to update my README.md. Actually I am also a novice to Tensorflow. Before you mention the `.ckpt.meta` file, I don’t even know its usefulness 🤣, so I really appreciate your comment.

Here is a simple bash to run my model. Firstly, download the model and unzip it into `BERT-Pruning` directory, unzip it, then run this bash to train one epoch on SST-2:

```bash
export BERT_DIR=`pwd`
export CHECKPOINT=SST-2_85%_t=0.8
export OUTPUT_DIR=$BERT_DIR/SST-2_Pruning

task_name="SST-2"
batch_size="32"
max_seq_length="128"
fine_tune_epoch="1"
learning_rate="0.0001"
learning_rate_warmup="200"
lambda_lr="10.0"
alpha_lr="5.0"
target_sparsity="0.95"
target_sparsity_warmup="4000"
hidden_dropout_prob="0.1"
attention_probs_dropout_prob="0.1"
regularization_scale="0"
factorized="true"

python ./flop/run_classifier.py \
    --task_name=$task_name \
    --do_train=true \
    --do_eval=true \
    --data_dir=$BERT_DIR/datasets/$task_name/ \
    --vocab_file=$BERT_DIR/$CHECKPOINT/vocab.txt \
    --bert_config_file=$BERT_DIR/$CHECKPOINT/bert_config.json \
    --init_checkpoint=$BERT_DIR/$CHECKPOINT/bert_model.ckpt \
    --max_seq_length=$max_seq_length \
    --train_batch_size=$batch_size \
    --learning_rate=$learning_rate \
    --num_train_epochs=$fine_tune_epoch \
    --learning_rate_warmup=$learning_rate_warmup \
    --lambda_learning_rate=$lambda_lr \
    --alpha_learning_rate=$alpha_lr \
    --target_sparsity=$target_sparsity \
    --hidden_dropout_prob=$hidden_dropout_prob \
    --attention_probs_dropout_prob=$attention_probs_dropout_prob \
    --target_sparsity_warmup=$target_sparsity_warmup \
    --regularization_scale=$regularization_scale \
    --output_dir=$OUTPUT_DIR/$CHECKPOINT \
    --factorized=$factorized
```
Before first trainning, the program will save a checkpoint, then you can force to close the program.
You can find `.ckpt.meta` under the directory `.../BERT-Pruning/SST-2_Pruning/SST-2_85%_t=0.8`. In my case, there are several files in my path `BERT-Pruning/SST-2_Pruning/SST-2_85%_t=0.8/2021-03-18-12:20:48`:
```
checkpoint  eval.tf_record  events.out.tfevents.1616041273.amax  graph.pbtxt  model.ckpt-0.data-00000-of-00001  model.ckpt-0.index  model.ckpt-0.meta  train.tf_record
```
Then I run:
```python
import tensorflow as tf
sess = tf.Session()
saver = tf.train.import_meta_graph('model.ckpt-0.meta')
saver.restore(sess, 'model.ckpt-0')
```

No error 👍! But I have not verified its performance on SST-2 dataset.
**And my question is, if the model is loaded in this way, how do we feed the data to the model?**

BTW, you can evaluate that downloaded model on SST-2 without training, by simply setting the flag `--do_train=false` and `--do_eval=true`.

**Comment by akhauriyash** [comment]
Thank you for your help! 
Really appreciate it. :)
